/**
 * registry.ts — built-in tool name → executor mapping.
 *
 * Kept separate from the permission/sandbox pipeline so adding a tool only
 * touches definitions + registry + (if needed) capability/profile sets.
 */
import { runBash } from './bash';
import { runWebFetch, runWebSearch } from './network';
import {
  runRead,
  runReadImage,
  runWrite,
  runEdit,
  runStrReplaceEditor,
  runDelete,
  runGitCommit,
  runGrep,
  runGlob,
} from './file-tools';
import {
  runCronCreate,
  runCronDelete,
  runCronList,
  runJobKill,
  runJobList,
  runJobOutput,
  runScheduleCreate,
  runScheduleDelete,
  runScheduleList,
  runTaskList,
  runTaskOutput,
  runTaskStop,
} from './runtime';
import {
  runAskUser,
  runListSkills,
  runPwsh,
  runReadSkill,
  runReadSpill,
  runRunCode,
  runRunWorkflow,
  runSessionQuery,
} from './execution';
import { runLSPTool } from './lsp';
import { runReviewArtifact } from './review';
import { runAgentTool, runEnterPlanMode, runExitPlanMode, runNotebookEdit, runTodoWrite } from './internal';
import { runEnterWorktree } from './worktree';
import {
  runInspectRuntime,
  runPtyToolHandler,
  runTerminalClose,
  runTerminalList,
  runTerminalOpen,
  runTerminalRead,
  runTerminalSend,
  runTerminalSignal,
  runWriteSkill,
} from './terminal';
import {
  runDriveList,
  runDriveRead,
  runNotionCreatePage,
  runNotionSearch,
  runReadDocument,
  runSlackListChannels,
  runSlackPostMessage,
  runWriteDocument,
} from './integrations';
import {
  runCreateGoal,
  runGetGoal,
  runInterruptAgent,
  runListAgents,
  runMountPlugin,
  runRalph,
  runReport,
  runSendMessage,
  runUnmountPlugin,
  runUpdateGoal,
} from './agents';
import { runSessionEventRead, runSessionEventSearch, runSessionTrace } from './session';

export const toolRegistry = {
  ListSkills: runListSkills,
  ReadSkill: runReadSkill,
  SessionQuery: runSessionQuery,
  ReadSpill: runReadSpill,
  AskUser: runAskUser,
  ReadDocument: runReadDocument,
  WriteDocument: runWriteDocument,
  SlackListChannels: runSlackListChannels,
  SlackPostMessage: runSlackPostMessage,
  DriveList: runDriveList,
  DriveRead: runDriveRead,
  NotionSearch: runNotionSearch,
  NotionCreatePage: runNotionCreatePage,
  Pty: runPtyToolHandler,
  TerminalOpen: runTerminalOpen,
  TerminalList: runTerminalList,
  TerminalRead: runTerminalRead,
  TerminalSend: runTerminalSend,
  TerminalSignal: runTerminalSignal,
  TerminalClose: runTerminalClose,
  InspectRuntime: runInspectRuntime,
  WriteSkill: runWriteSkill,
  RunWorkflow: runRunWorkflow,
  RunCode: runRunCode,
  Bash: runBash,
  Read: runRead,
  ReadImage: runReadImage,
  Write: runWrite,
  Edit: runEdit,
  StrReplaceEditor: runStrReplaceEditor,
  Delete: runDelete,
  Grep: runGrep,
  Glob: runGlob,
  WebFetch: runWebFetch,
  WebSearch: runWebSearch,
  TodoWrite: runTodoWrite,
  Agent: runAgentTool,
  CronCreate: runCronCreate,
  CronDelete: runCronDelete,
  CronList: runCronList,
  ScheduleCreate: runScheduleCreate,
  ScheduleDelete: runScheduleDelete,
  ScheduleList: runScheduleList,
  TaskOutput: runTaskOutput,
  TaskStop: runTaskStop,
  TaskList: runTaskList,
  JobList: runJobList,
  JobOutput: runJobOutput,
  JobKill: runJobKill,
  EnterPlanMode: runEnterPlanMode,
  ExitPlanMode: runExitPlanMode,
  NotebookEdit: runNotebookEdit,
  EnterWorktree: runEnterWorktree,
  LSP: runLSPTool,
  ReviewArtifact: runReviewArtifact,
  GitCommit: runGitCommit,
  ListAgents: runListAgents,
  SendMessage: runSendMessage,
  InterruptAgent: runInterruptAgent,
  Report: runReport,
  GetGoal: runGetGoal,
  CreateGoal: runCreateGoal,
  UpdateGoal: runUpdateGoal,
  MountPlugin: runMountPlugin,
  UnmountPlugin: runUnmountPlugin,
  Ralph: runRalph,
  Pwsh: runPwsh,
  SessionEventSearch: runSessionEventSearch,
  SessionEventRead: runSessionEventRead,
  SessionTrace: runSessionTrace,
};
